In [1]:
import pandas as pd
import numpy as np

In [2]:
data={
    'Name':['A','B','C','D','E','f','G','H'],
    'Maths':[85,90,np.nan,77,58,81,69,78],
    'Science':[88,91,55,np.nan,70,56,66,110],
    'English':[56,51,99,77,89,np.nan,77,88],
    'Attendance':[90,95,85,60,105,80,np.nan,88]
}

df=pd.DataFrame(data)

In [3]:
df

  Name  Maths  Science  English  Attendance
0    A   85.0     88.0     56.0        90.0
1    B   90.0     91.0     51.0        95.0
2    C    NaN     55.0     99.0        85.0
3    D   77.0      NaN     77.0        60.0
4    E   58.0     70.0     89.0       105.0
5    f   81.0     56.0      NaN        80.0
6    G   69.0     66.0     77.0         NaN
7    H   78.0    110.0     88.0        88.0

In [4]:
df.describe()

           Maths     Science    English  Attendance
count   7.000000    7.000000   7.000000    7.000000
mean   76.857143   76.571429  76.714286   86.142857
std    10.605479   20.411248  17.632492   13.993196
min    58.000000   55.000000  51.000000   60.000000
25%    73.000000   61.000000  66.500000   82.500000
50%    78.000000   70.000000  77.000000   88.000000
75%    83.000000   89.500000  88.500000   92.500000
max    90.000000  110.000000  99.000000  105.000000

In [5]:
df.dtypes

Name           object
Maths         float64
Science       float64
English       float64
Attendance    float64
dtype: object

In [6]:
df.isnull().sum()

Name          0
Maths         1
Science       1
English       1
Attendance    1
dtype: int64

In [7]:
df['Maths']= df['Maths'].fillna(df['Maths'].mean())
df['Science']= df['Science'].fillna(df['Science'].mean())
df['English']= df['English'].fillna(df['English'].mean())
df['Attendance']= df['Attendance'].fillna(df['Attendance'].mean())

In [8]:
df

  Name      Maths     Science    English  Attendance
0    A  85.000000   88.000000  56.000000   90.000000
1    B  90.000000   91.000000  51.000000   95.000000
2    C  76.857143   55.000000  99.000000   85.000000
3    D  77.000000   76.571429  77.000000   60.000000
4    E  58.000000   70.000000  89.000000  105.000000
5    f  81.000000   56.000000  76.714286   80.000000
6    G  69.000000   66.000000  77.000000   86.142857
7    H  78.000000  110.000000  88.000000   88.000000

In [9]:
df.isnull().sum()

Name          0
Maths         0
Science       0
English       0
Attendance    0
dtype: int64

In [10]:
df['Maths']= np.where(df['Maths']>100, 100, df['Maths'])
df['Science']= np.where(df['Science']>100, 100, df['Science'])
df['Attendance']= np.where(df['Attendance']>100, 100, df['Attendance'])

In [11]:
df

  Name      Maths     Science    English  Attendance
0    A  85.000000   88.000000  56.000000   90.000000
1    B  90.000000   91.000000  51.000000   95.000000
2    C  76.857143   55.000000  99.000000   85.000000
3    D  77.000000   76.571429  77.000000   60.000000
4    E  58.000000   70.000000  89.000000  100.000000
5    f  81.000000   56.000000  76.714286   80.000000
6    G  69.000000   66.000000  77.000000   86.142857
7    H  78.000000  100.000000  88.000000   88.000000

In [12]:
Q1= df['Maths'].quantile(0.25)
Q3= df['Maths'].quantile(0.75)
IQR= Q3-Q1
lower= Q1-1.5*IQR
upper=Q3+1.5*IQR

outliers= df[(df['Maths']<lower) | (df['Maths']> upper)]

In [13]:
outliers

  Name  Maths  Science  English  Attendance
4    E   58.0     70.0     89.0       100.0

In [14]:
df['Maths_log']= np.log(df["Maths"])

In [15]:
df

  Name      Maths     Science    English  Attendance  Maths_log
0    A  85.000000   88.000000  56.000000   90.000000   4.442651
1    B  90.000000   91.000000  51.000000   95.000000   4.499810
2    C  76.857143   55.000000  99.000000   85.000000   4.341948
3    D  77.000000   76.571429  77.000000   60.000000   4.343805
4    E  58.000000   70.000000  89.000000  100.000000   4.060443
5    f  81.000000   56.000000  76.714286   80.000000   4.394449
6    G  69.000000   66.000000  77.000000   86.142857   4.234107
7    H  78.000000  100.000000  88.000000   88.000000   4.356709

In [16]:
df['Science']= (df['Science']- df['Science'].min())/(df['Science'].max()- df['Science'].min())

In [17]:
df

  Name      Maths   Science    English  Attendance  Maths_log
0    A  85.000000  0.733333  56.000000   90.000000   4.442651
1    B  90.000000  0.800000  51.000000   95.000000   4.499810
2    C  76.857143  0.000000  99.000000   85.000000   4.341948
3    D  77.000000  0.479365  77.000000   60.000000   4.343805
4    E  58.000000  0.333333  89.000000  100.000000   4.060443
5    f  81.000000  0.022222  76.714286   80.000000   4.394449
6    G  69.000000  0.244444  77.000000   86.142857   4.234107
7    H  78.000000  1.000000  88.000000   88.000000   4.356709

In [20]:
df.describe()

           Maths   Science    English  Attendance  Maths_log
count   8.000000  8.000000   8.000000    8.000000   8.000000
mean   76.857143  0.451587  76.714286   85.517857   4.334240
std     9.818766  0.367905  16.324515   12.000957   0.135456
min    58.000000  0.000000  51.000000   60.000000   4.060443
25%    74.892857  0.188889  71.535714   83.750000   4.314988
50%    77.500000  0.406349  77.000000   87.071429   4.350257
75%    82.000000  0.750000  88.250000   91.250000   4.406500
max    90.000000  1.000000  99.000000  100.000000   4.499810

In [ ]:
(